### ISSUE TITLE
Support partial trust environments

### ISSUE THREAD

**Issue by benempson** [FakeItEasy/FakeItEasy#1048]
As per the later part of the discussion held on https://github.com/FakeItEasy/FakeItEasy/issues/414

I am running tests in a partial trust environment, because the production environment is partial trust (out of my control) and code which runs in full trust fails to run in partial trust.

I'm using this to simulate / generate a partial trust environment: https://github.com/xunit/samples.xunit/tree/master/PartialTrustExample

Any code which is running in partial trust is getting an error 

```
Inheritance security rules violated while overriding member: 'Castle.Core.Logging.LevelFilteredLogger.InitializeLifetimeService()'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.":"Castle.Core.Logging.LevelFilteredLogger.InitializeLifetimeService()"

at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator..ctor(CastleDynamicProxyInterceptionValidator interceptionValidator)
at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_23(DictionaryContainer c)
at FakeItEasy.IoC.DictionaryContainer.SingletonResolver1.UnresolvedState.Resolve(DictionaryContainer container)
at FakeItEasy.IoC.DictionaryContainer.SingletonResolver1.Resolve(DictionaryContainer container)
at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_01.b__0(DictionaryContainer c)
at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
at FakeItEasy.ServiceLocator.ResolveT
at FakeItEasy.RootModule.<>c.b__0_25(DictionaryContainer c)
at FakeItEasy.IoC.DictionaryContainer.SingletonResolver1.UnresolvedState.Resolve(DictionaryContainer container)
at FakeItEasy.IoC.DictionaryContainer.SingletonResolver1.Resolve(DictionaryContainer container)
at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_01.<Register>b__0(DictionaryContainer c)
at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
at FakeItEasy.ServiceLocator.Resolve[T]()
at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_22(DictionaryContainer c)
at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_01.b__0(DictionaryContainer c)
at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
at FakeItEasy.ServiceLocator.ResolveT
at FakeItEasy.A.get_FakeAndDummyManager()
at FakeItEasy.A.Fake[T](Action1 optionsBuilder)
at FakeItEasy.A.Fake[T]()
etc etc
```

Unfortunately I can't partition my tests out, as I'm dependent on other libraries which in turn are linked to FakeItEasy, I'm not consuming FakeItEasy directly. I'm also dependent on version 2.3.3 of FakeItEasy since upgrading beyond that breaks the other library.

**Comment by blairconrad** [comment]
Thanks for creating this, @benArrayx.

I am sad to say that I don't think there will be much appetite for creating a 2.x release with expanded support for partial trust environments. Perhaps something can be done to make the other library (is it a well-known one? We may be able to help) work with FakeItEasy 3.2.0+.

**Comment by benArrayx** [comment]
I understand, I've been able to update to 3.2 and still the same thing happens. I have also downloaded the source at 3.3 and tried to apply SecurityCritical attributes where it seemed necessary - to no avail :(

It did slightly change the stacktrace:

`   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator..ctor(CastleDynamicProxyInterceptionValidator interceptionValidator)
   at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_23(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.UnresolvedState.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_0`1.<Register>b__0(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
   at FakeItEasy.ServiceLocator.Resolve[T]()
   at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_25(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.UnresolvedState.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_0`1.<Register>b__0(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
   at FakeItEasy.ServiceLocator.Resolve[T]()
   at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_22(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_0`1.<Register>b__0(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
   at FakeItEasy.ServiceLocator.Resolve[T]()
   at FakeItEasy.A.get_FakeAndDummyManager()
   at FakeItEasy.A.Fake[T](Action`1 optionsBuilder)
   at FakeItEasy.A.Fake[T]()`

I'm no expert on security either, so I don't have much of a clue of where to go from here I'm afraid!

(On a side note, I've got a failing test in my repo: TypeCatalogueTests.Should_be_able_to_get_types_from_external_assembly() - this fail is in your master as well as in my branch, therefore nothing to do with my changes).

**Comment by blairconrad** [comment]
Hi, @benArrayx. Aside from formatting (some "`"s and type params disappearing), the stack traces look the same to me.

I'm curious about the failing `TypeCatalogueTests.Should_be_able_to_get_types_from_external_assembly`, but probably best to pursue it outside this issue.

**Comment by blairconrad** [comment]
@benArrayx, I think `[SecurityCritical]` needs to be applied to the overridden member. Me, when I add a test like

```c#
[PartialTrustFact]
public void Failing()
{
    A.Fake<Person>();
}
```
(and work around the error I get with the file access permissions) I still see

```
Warning: FakeItEasy failed to get types from assembly 'FakeItEasy, Version=3.3.0.0, Culture=neutral, PublicKeyToken=eff28e2146d5fd2c' while scanning for extension points. Any IArgumentValueFormatters, IDummyFactories, and IFakeOptionsBuilders in that assembly will not be available.
  Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   FakeItEasy.IntegrationTests.FakingClassesTests.Failing [FAIL]
      System.TypeLoadException : Inheritance security rules violated while overriding member: 'Castle.DynamicProxy.ProxyGenerationOptions.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.
      Stack Trace:
            at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.GenerateProxy(Type typeOfProxy, IEnumerable`1 additionalInterfacesToImplement, IEnumerable`1 argumentsForConstructor, IEnumerable`1 attributes, IFakeCallProcessorProvider fakeCallProcessorProvider)
            at FakeItEasy.Creation.ProxyGeneratorSelector.GenerateProxy(Type typeOfProxy, IEnumerable`1 additionalInterfacesToImplement, IEnumerable`1 argumentsForConstructor, IEnumerable`1 attributes, IFakeCallProcessorProvider fakeCallProcessorProvider)
            at FakeItEasy.Creation.FakeObjectCreator.GenerateProxy(Type typeOfFake, IProxyOptions proxyOptions, IEnumerable`1 argumentsForConstructor)
            at FakeItEasy.Creation.FakeObjectCreator.CreateFake(Type typeOfFake, IProxyOptions proxyOptions, IDummyValueCreationSession session, Boolean throwOnFailure)
            at FakeItEasy.Creation.DefaultFakeAndDummyManager.CreateFake(Type typeOfFake, Action`1 optionsBuilder)
            at FakeItEasy.A.Fake[T](Action`1 optionsBuilder)
            at FakeItEasy.IntegrationTests.FakingClassesTests.Failing()
```
. The thing is, I don't see where we're overriding the method `GetObjectData` method. We instantiate a `ProxyGenerationOptions` class, but that's it. And adding `SecurityCritical` to `GenerateProxy` makes no difference.

At this point, I'm at a loss. Maybe @jimmyheaddon can shed some more light, as he'd originally suggested adding `SecurityCritical`s. Or maybe @jonorossi (sorry to pull you in) has seen a complaint like this before, as I don't think we're doing anything incredibly out of the ordinary here.

**Comment by jonorossi** [comment]
We haven't received any reports on partial trust problems for many years, I know there are some inconsistently applied security attributes to some Castle Core code, however nothing has really changed much with them in probably 5 years.

I don't have the time to dig into what could be going on, I've purged most of my partial trust knowledge 😉 , however if the problem does turn out to be in a Castle library jump over there with an issue or pull request and we'll try to get it in.

**Comment by blairconrad** [comment]
Thanks, @jonorossi. After I wrote last night, I thought that _maybe_ Castle.Core had a type that extended `ProxyGenerationOptions`, but with an inconsistent attribute on `GetObjectData`, but I just checked and it appears not to be the case.

**Comment by thomaslevesque** [comment]
Related: https://stackoverflow.com/questions/48355591/how-can-i-implement-iserializable-in-net-4-without-violating-inheritance-secur

**Comment by blairconrad** [comment]
@thomaslevesque, I can't imagine us ever touching this issue unless it comes up again. And maybe not even then. Objections to closing?

**Comment by thomaslevesque** [comment]
> Objections to closing?

Not a single one!
