### ISSUE TITLE
CallToSet fails when setting base interface property

### ISSUE THREAD

**Issue by Heteroculturalism** [FakeItEasy/FakeItEasy#1316]
[Bug.zip](https://github.com/FakeItEasy/FakeItEasy/files/1731953/Bug.zip)

Run attached, the CallToSet method fails when setting a base interface property.

**Comment by blairconrad** [comment]
Thanks for reporting this, @Heteroculturalism. Are you interested in pursuing a fix?

**Comment by blairconrad** [comment]
To save future readers the trouble of unpacking the zip, here's the reproduction:

```c#
public interface IBaseInterface
{
    string TheProperty { get; set; }
}

public interface IDerivedInterface : IBaseInterface
{
}

[Test]
public void Foo()
{
    var derivedInterface = A.Fake<IDerivedInterface>();

    A.CallToSet(() => derivedInterface.TheProperty).Invokes(() => { });
}
```

and the error:

```
Test 'ClassLibrary3.CannotFakeBaseInterface.Foo' failed: System.ArgumentException : The property TheProperty does not have a setter.
	at FakeItEasy.Configuration.PropertyExpressionHelper.BuildSetterFromGetter[TValue](ParsedCallExpression parsedCallExpression)
	at FakeItEasy.Configuration.FakeConfigurationManager.CallToSet[TValue](Expression`1 propertySpecification)
	at FakeItEasy.A.CallToSet[TValue](Expression`1 propertySpecification)
	CannotFakeBaseInterface.cs(23,0): at ClassLibrary3.CannotFakeBaseInterface.Foo()
```

**Comment by Heteroculturalism** [comment]
I don't have the bandwidth to fix the issue myself but I thought I'd at least report the issue.

**Comment by blairconrad** [comment]
No worries. Sometimes people like to fix the bugs they report. We'll put it in the queue.
Again, thanks for the report!

**Comment by thomaslevesque** [comment]
This was a regression introduced in 4.4.0. We should release a 4.4.1 with the fix.

**Comment by blairconrad** [comment]
Or 4.1.0, since we have an enhancement in the analyzer.

**Comment by thomaslevesque** [comment]
True. Anyway, we didn't follow the normal process for a hotfix, so we might as well release a minor.

**Comment by thomaslevesque** [comment]
This bug has been fixed in [FakeItEasy 4.5.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.5.0).

Thanks for the report @Heteroculturalism!
