### ISSUE TITLE
Not compatible with dotnetcore 2.1-rc1-final

### ISSUE THREAD

**Issue by ryanwischkaemper** [FakeItEasy/FakeItEasy#1345]
Dotnetcore 2.1-rc1 was [released the other day](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-net-core-2-1-rc-1/). I updated a class library and it's accompanying unit test project to 2.1-rc1 (it was previously targeting 2.0). 

Now I get errors in my tests like this:

`System.NotSupportedException: 'Cannot create boxed ByRef-like values.'` (stack trace below)

A lot of other tests are breaking with the same error, but this is a simpler one. 

`dotnet --version` is **2.1.300-rc1-008673**

### Test Method
```csharp
[TestMethod]
        public async Task GetValue_WhenRequestedByMoreThanOneTask_ShouldOnlyCallValueFactoryOnce()
        {
            var fakeValueFactory = A.Fake<Func<string, Task<string>>>();

            var sut = new ThreadSafeAsyncCache<string, string>(fakeValueFactory);

	        var callingTasks = Enumerable.Range(0,3).Select(x => sut.GetValue(A.Dummy<string>())).ToArray();

            await Task.WhenAll(callingTasks);

            A.CallTo(() => fakeValueFactory.Invoke(A.Dummy<string>())).MustHaveHappened(Repeated.Exactly.Once);
        }
```

### Class Being Tested
```csharp
    public class ThreadSafeAsyncCache<TKey, TValue>
    {
        private readonly Func<TKey, Task<TValue>> _valueFactory;
        private readonly ConcurrentDictionary<TKey, Lazy<Task<TValue>>> _map;

        public ThreadSafeAsyncCache(Func<TKey, Task<TValue>> valueFactory)
        {
            if(valueFactory == null) throw new ArgumentNullException(nameof(valueFactory));
            _valueFactory = valueFactory;
            _map = new ConcurrentDictionary<TKey, Lazy<Task<TValue>>>();
        }

        public Task<TValue> GetValue(TKey key)
        {
            if(key == null) throw new ArgumentNullException(nameof(key));
            return _map.GetOrAdd(key,
                x => new Lazy<Task<TValue>>(() => _valueFactory(x)))?.Value;
        }
    }
```

Stack Trace:

```
System.NotSupportedException: Cannot create boxed ByRef-like values.
    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at FakeItEasy.Creation.DummyValueResolver.ResolveByActivatingValueTypeStrategy.TryCreateDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 83
   at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValueWithAllAvailableStrategies(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 66
   at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 45
   at FakeItEasy.Creation.FakeObjectCreator.ResolveConstructorArguments(ConstructorInfo constructor, DummyCreationSession session, IDummyValueResolver resolver) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs:line 61
   at FakeItEasy.Creation.FakeObjectCreator.<>c__DisplayClass5_0.<ResolveConstructors>b__0(ConstructorInfo constructor) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs:line 42
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FakeItEasy.Creation.FakeObjectCreator.TryCreateFakeWithDummyArgumentsForConstructor(Type typeOfFake, IProxyOptions proxyOptions, DummyCreationSession session, IDummyValueResolver resolver, String failReasonForDefaultConstructor, Boolean throwOnFailure) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs:line 87
   at FakeItEasy.Creation.FakeObjectCreator.CreateFake(Type typeOfFake, IProxyOptions proxyOptions, DummyCreationSession session, IDummyValueResolver resolver, Boolean throwOnFailure) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs:line 31
   at FakeItEasy.RootModule.ResolverFakeObjectCreator.TryCreateFakeObject(DummyCreationSession session, Type typeOfFake, DummyValueResolver resolver, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\RootModule.cs:line 146
   at FakeItEasy.Creation.DummyValueResolver.ResolveByCreatingFakeStrategy.TryCreateDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 107
   at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValueWithAllAvailableStrategies(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 66
   at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 45
   at FakeItEasy.Creation.DummyValueResolver.ResolveByCreatingTaskStrategy.TryCreateDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 132
   at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValueWithAllAvailableStrategies(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 66
   at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs:line 45
   at FakeItEasy.Core.InterceptedFakeObjectCallExtensions.GetDefaultReturnValue(IInterceptedFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\Core\InterceptedFakeObjectCallExtensions.cs:line 12
   at FakeItEasy.Core.DefaultReturnValueRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\DefaultReturnValueRule.cs:line 20
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 151
   at FakeItEasy.Creation.DelegateProxies.DelegateProxyGenerator.DelegateCallInterceptedEventRaiser.Raise(Object[] arguments) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DelegateProxies\DelegateProxyGenerator.cs:line 182
   at lambda_method(Closure , String )
```

**Comment by blairconrad** [comment]
Thanks for raising this, @ryanwischkaemper. I've not yet jumped on the 2.1-rc1 bandwagon yet, but will install now and start investigating.

**Comment by blairconrad** [comment]
I've managed to reproduce, and have found a simpler test case to do so:

```c#
var dummy = A.Dummy<string>();
```

Stack trace:

```
System.NotSupportedException : Cannot create boxed ByRef-like values.
Stack Trace:
     at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
     at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
     at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs(83,0): at FakeItEasy.Creation.DummyValueResolver.ResolveByActivatingValueTypeStrategy.TryCreateDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs(66,0): at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValueWithAllAvailableStrategies(DummyCreationSession session, Type typeOfDummy, Object& result)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs(45,0): at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs(61,0): at FakeItEasy.Creation.FakeObjectCreator.ResolveConstructorArguments(ConstructorInfo constructor, DummyCreationSession session, IDummyValueResolver resolver)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs(42,0): at FakeItEasy.Creation.FakeObjectCreator.<>c__DisplayClass5_0.<ResolveConstructors>b__0(ConstructorInfo constructor)
     at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
     at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
     at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs(87,0): at FakeItEasy.Creation.FakeObjectCreator.TryCreateFakeWithDummyArgumentsForConstructor(Type typeOfFake, IProxyOptions proxyOptions, DummyCreationSession session, IDummyValueResolver resolver, String failReasonForDefaultConstructor, Boolean throwOnFailure)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\FakeObjectCreator.cs(31,0): at FakeItEasy.Creation.FakeObjectCreator.CreateFake(Type typeOfFake, IProxyOptions proxyOptions, DummyCreationSession session, IDummyValueResolver resolver, Boolean throwOnFailure)
  C:\projects\fakeiteasy\src\FakeItEasy\RootModule.cs(146,0): at FakeItEasy.RootModule.ResolverFakeObjectCreator.TryCreateFakeObject(DummyCreationSession session, Type typeOfFake, DummyValueResolver resolver, Object& result)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs(107,0): at FakeItEasy.Creation.DummyValueResolver.ResolveByCreatingFakeStrategy.TryCreateDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs(66,0): at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValueWithAllAvailableStrategies(DummyCreationSession session, Type typeOfDummy, Object& result)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\DummyValueResolver.cs(45,0): at FakeItEasy.Creation.DummyValueResolver.TryResolveDummyValue(DummyCreationSession session, Type typeOfDummy, Object& result)
  C:\projects\fakeiteasy\src\FakeItEasy\Creation\DefaultFakeAndDummyManager.cs(29,0): at FakeItEasy.Creation.DefaultFakeAndDummyManager.CreateDummy(Type typeOfDummy)
  C:\projects\fakeiteasy\src\FakeItEasy\A.cs(86,0): at FakeItEasy.A.Dummy[T]()
  D:\Sandbox\FIE-dotnetcore-2.1rc1\UnitTest1.cs(12,0): at FIE_dotnetcore_2._1rc1.UnitTest1.Test1()
```

I suspect that something's changed in the signature of the string constructors, and we're now trying to call some forbidden constructor.

Sadly, I'm at the Day Job now, and will not be able to investigate further until either very late tonight or sometime tomorrow morning.

**Comment by ryanwischkaemper** [comment]
@blairconrad Awesome, thanks for looking into this so quickly. I pulled in Moq and verified that it was working on dotnetcore 2.1-rc1, but it'd be a lot of work to remove FakeItEasy from all of our test cases. Plus we like FakeItEasy more :D

**Comment by ryanwischkaemper** [comment]
@blairconrad I did a little digging on this issue, and I'm a little curious as to how you'll implement the fix. The exception is thrown in the `ResolveByActivatingValueTypeStrategy`, but the tricky part is that the new `Span<T>` and `ReadOnlySpan<T>` are value types but they can only live on the stack and can't be boxed. 

So the question is, how do you check for those specific types and move on to the next resolution strategy? Projects that target dotnetcore 2.1-rc1 can use a new extension method off of `Type` named `IsByRefLike` - that correctly identifies the new `ref struct` behavior of `Span<T>`. But, in the case of this code base (and many others), that method is not available. I came across this [MSDN blog post](https://blogs.msdn.microsoft.com/mazhou/2018/03/02/c-7-series-part-9-ref-structs/) that talks about the metadata associated with these new stack-only value types, and I quote:
>Ref struct is available in C# 7.2. This feature needs compiler level changes to work, to be backward compatible with previously  compiler generated assemblies,. C# 7.2 compiler emits [Obsolete] and [IsByRefLike] attributes for ref struct declarations.
If any old assemblies references library that contains ref struct types, the [Obsolete] attribute will effect and block the code from compiling.

So.. *a* solution is to check for the presence of the `Obsolete` attribute in addition to the existing type checks in the `ResolveByActivatingValueTypeStrategy`. I made those changes locally and verified it all worked - all FakeItEasy tests pass and all of the tests in my class library pass as well. It doesn't feel like a great solution (and that's why I haven't put up a PR) because any other value types using the `Obsolete` attribute would be excluded from this resolution strategy. It looks like this
```csharp
        private class ResolveByActivatingValueTypeStrategy : ResolveStrategy
        {
            public override bool TryCreateDummyValue(DummyCreationSession session, Type typeOfDummy, out object result)
            {
                result = default(object);

                if (typeOfDummy.GetTypeInfo().IsValueType && typeOfDummy != typeof(void) &&
                    !typeOfDummy.GetTypeInfo().GetCustomAttributes(typeof(ObsoleteAttribute), true).Any())
                {
                    result = Activator.CreateInstance(typeOfDummy);
                    return true;
                }

                return false;
            }
        }
```

**Comment by blairconrad** [comment]
Wow, thanks for all that @ryanwischkaemper. I'm behind the curve on these sorts of things, but I wonder if we couldn't check for `IsByRefLike` attributes instead. There's no reason why FakeItEasy couldn't build with C# 7.2, I think. But perhaps the type would still not be available to us and we'd have to refer to it by name. Not ideal.

I'd not done the research you had, but I'd anticipated that we'd have problems detecting the `IsByRefLike`ness of the type. My leading alternative is just to catch the exception. There are a number of reasons why constructors might throw (it's not ideal, but it might happen), and there's no reason why one throwing constructor should defeat the whole process of creating a Dummy (or Fake) when there might be other constructors that would pass (as is the case for `String`). It's a bit of a sledgehammer approach, and not as nice as detecting this known failure case, but it's a start, and one that might be useful even alongside a "nice" solution.

A good chunk of Team FakeItEasy are off now, and this may delay a release somewhat. While we're working on it (and if you want to submit other suggestions and/or PRs, we welcome them), is using your built ad hoc FakeItEasy package an option, just to keep you going?

**Comment by ryanwischkaemper** [comment]
@blairconrad Yes we'll use this temporary FakeItEasy package until the FakeItEasy team comes up with the desired resolution. Thanks again for the quick response on this!

**Comment by blairconrad** [comment]
@ryanwischkaemper, I just saw that. Feel free to ignore my parallel note in #1349 about trying out the code in that PR. Then again, don't let me stop you, if you're so inclined.

**Comment by ryanwischkaemper** [comment]
@blairconrad I checked out your PR and it works with all of our tests. Thanks!

**Comment by blairconrad** [comment]
Given that the original symptom was resolved by #1348, I think we can do 2 more things here, which are somewhat related:

1. add tests that run under .NET CORE 2.1 RC1 (and ultimately 2.1 when it's released) and
2. as a bonus, detect `IsByRefLike` types and refused to create them as Dummies, rather than attempting to create them and deal with the exception that's thrown

Shall we close this issue in favour of the two I mention here (and maybe other(s) that I've not thought of)?

**Comment by thomaslevesque** [comment]
Sounds good to me
