### ISSUE TITLE
Unable to cast object of type 'Castle.Proxies.ObjectProxy_15' to type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ITempDataDictionaryFactory'

### ISSUE THREAD

**Issue by hhk1907** [FakeItEasy/FakeItEasy#1453]
When I fake httpContext, the return View throws the exception: 

> Unable to cast object of type 'Castle.Proxies.ObjectProxy_15' to type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ITempDataDictionaryFactory'.

I need to fake HttpContext because in the code there is a check of User.IsInRole(<string>) which will return a boolean.

TestController:

```
// Arrange
projectController.ControllerContext.HttpContext = A.Fake<HttpContext>();
projectController.ControllerContext.HttpContext.User = A.Fake<ClaimsPrincipal>();
A.CallTo(() => projectController.ControllerContext.HttpContext.User.IsInRole(A<string>.Ignored)).Returns(false);

// ACT
ViewResult result = await projectController.Create() as ViewResult;
```

The error occurs at Controller:
```
public async Task<IActionResult> Create() {
var model = new CreateProjectViewModel();
return View(model);
}
```

If I don't fake httpContext, the httpContext will be null and the User.IsInRole cannot be executed.

**Comment by thomaslevesque** [comment]
Hi @hhk1907,

Could you please provide the stack trace of the exception?

**Comment by hhk1907** [comment]
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Mvc.Controller.get_TempData()
>    at Microsoft.AspNetCore.Mvc.Controller.View(String viewName, Object model)
> at Web.Controllers.ProjectController.Create() in ....

**Comment by thomaslevesque** [comment]
Ah, I see. The problem seems to be here: https://github.com/aspnet/Mvc/blob/bd2754160e2deed18d73ae5be5f88ead82874d86/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Controller.cs#L72

`RequestServices` must be a fake `IServiceProvider`, which just returns a fake object (the generic `GetRequiredService<T>` method is just an extension method, the "real" method isn't generic and has `Object` as its return type, so FakeItEasy just creates a fake `Object` since it doesn't know what else to return).

You could do something like this:

```csharp
A.CallTo(() => httpContext.RequestServices.GetService(A<Type>.Ignored)).ReturnsLazily((Type type) => FakeItEasy.Sdk.Create.Fake(type));
```

Or you could set RequestServices to a real service provider.

**Comment by thomaslevesque** [comment]
You're welcome! Glad it worked out for you
