### ISSUE TITLE
Have ReturnsNextFromSequence guard against null values

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1572]
… as @thomaslevesque [noted](https://github.com/FakeItEasy/FakeItEasy/pull/1571/files?utf8=%E2%9C%93&diff=unified&w=1#r255308117), neither overload does. 

```c#
public interface IFoo
{
    int M();
}

[Test]
public void Null()
{
    var fake = A.Fake<IFoo>();
    int[] results = null;
    A.CallTo(() => fake.M()).ReturnsNextFromSequence(results);
}
```

fails with error:

```
System.ArgumentNullException : Value cannot be null.
Parameter name: collection
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   at FakeItEasy.ReturnValueConfigurationExtensions.ReturnsNextFromSequence[T](IReturnValueConfiguration`1 configuration, T[] values) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 311
   at FakeItEasyQuestions2015.ReturnsNextFromSequence.Null() in …\ReturnNextFromSequence.cs:line 18
```

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 5.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.1.0).
