### ISSUE TITLE
Tests fail in Visual Studio 16.2 with could not load file or assembly

### ISSUE THREAD

**Issue by tomeeraerts** [FakeItEasy/FakeItEasy#1599]
Since updating to Visual Studio 2019 16.2 my tests keep failing with this error:
```bash
Message: 
    Test method Package.Tests.UnitTest1.TestMethod1 threw exception: 
    FakeItEasy.Core.FakeCreationException: 
      Failed to create fake of type xxxxxx:
        No usable default constructor was found on the type xxxxx.
        An exception of type System.IO.FileNotFoundException was caught during this call. Its message was:
        Could not load file or assembly 'xxxx, Version=x.x.x.x, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
           at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
           at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
           at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
           at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CreateType(TypeBuilder type) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType() in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1_0.<GenerateCode>b__0(String n, INamingScope s) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\CallConstraintDescriber.cs:line 0
           at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.GenerateInterfaceProxy(Type typeOfProxy, ReadOnlyCollection`1 additionalInterfacesToImplement, IEnumerable`1 attributes, IFakeCallProcessorProvider fakeCallProcessorProvider) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 41
    
```

I have a test project (targeting .net472 and using MsTest) that references a nuget package (let's call it A) that in turn needs another nuget package (B). I want to create a fake for an interface defined in A. This interface has a property of which the type is an interface defined in B. 

In Visual Studio 16.2 this now fails if the version of package B is different than the one listed by package with the error message above. 

Now there comes the strange thing:
- This only happens if i run the tests using the Test Explorer. If i run the tests using vstest.console, the tests are successful. 
- Using Visual Studio 16.1, everything works
- Visual Studio 2017 works
- Running the tests using resharper works
- In 16.3 preview, it's broken with the same error.

I've been able to reproduce this on different machines using a small project I created with just the things I need.

Reproduce steps on Visual Studio 16.2:
- Create 2 class libraries (X, Y) targeting .net standard and net461
- Define an interface IVeryImportantInterface in X
- Define an interface IMainInterface in Y
  - Add a property of  IVeryImportantInterface to the definition (it now has a dependency on X)
- Create nuget packages of both projects and use the same version (2.0.0)
- Create another nugetpackage of the X project and increase the version (3.0.0)
- Create a test project using mstest and .net472
   - Install FakeItEasy
   - Install package Y using packages.config
    - Add this code
    ```c#
        var test = A.Fake<IMainInterface>();
    ```
- The test should work
- Update the X package to the later version
- The test should now fail

I been trying to wrap my around it why it fails...

**Comment by blairconrad** [comment]
That's a lot to unpack, @tomeeraerts. I'm sorry you're having a bad time.

> I've been able to reproduce this on different machines using a small project I created with just the things I need.

Is it possible to share this project?

**Comment by tomeeraerts** [comment]
I've create a [repo](https://github.com/tomeeraerts/TestExplorer.Fakeit)
I also included the packages folder, that way you don't need to create the packages (they were created using dotnet pack).

There are two branches. One using the same versions where the test passes and one using different version where the test fails

**Comment by thomaslevesque** [comment]
The error is pretty clear, I think : MainPackage references LibPackage version 2.0.0.0, but the only version present is 3.0.0.0.
Why is MainPackage still referencing 2.0.0.0 ?

**Comment by tomeeraerts** [comment]
This is just a demo setup to reproduce/illustrate the problem. 

Imagine that the LibPackage is in entirely different repo controlled by another team. They now update the version of the package, even by a patch number. I install that new version in my application, which will make the tests fail because the version now installed is different from the version listed in MainPackage. 

This would mean I would have to create a new version of MainPackage listing the new dependency version and i have to do this for every dependency listed in all my packages. Otherwise i have failing tests...

**Comment by thomaslevesque** [comment]
Not sure what's going on, but as you mentioned, it's working fine with ReSharper and on the command line, so the problem must be in Test Explorer... They're probably doing something fishy with runtime assembly resolution. It doesn't look like it has anything to do with FakeItEasy.

**Comment by thomaslevesque** [comment]
As a workaround, you can resolve the assembly manually:

```csharp
        static UnitTest1()
        {
            AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>
            {
                var name = new AssemblyName(args.Name);
                if (name.Name == "LibPackage")
                {
                    return typeof(IVeryImportantInterface).Assembly;
                }

                return null;
            };
        }
```

This makes the test pass.

**Comment by tomeeraerts** [comment]
I'll try it out. Thanks!

**Comment by tomeeraerts** [comment]
My tests are now working again.

I created a more generic version. 
```c# 
        static UnitTest1()
        {
            AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>
            {
                 var requestedAssembly = new AssemblyName(args.Name);
                 var loadedAssemblies = AppDomain.CurrentDomain.GetAssemblies();
                 return loadedAssemblies.SingleOrDefault(x =>  x.GetName().Name.Equals(requestedAssembly.Name, StringComparison.OrdinalIgnoreCase));
            };
        }
```
I've put it here in cause anyone has the same problem.
