### ISSUE TITLE
Error when Fake uses in parameter 

### ISSUE THREAD

**Issue by eluchsinger** [FakeItEasy/FakeItEasy#1601]
I get a strange error when I try to create a fake of this interface. The error only occurs, when I have the generic type constraint *and* the `in` parameter modifier inside the `Publish` method. If I change the `in` modifier to `ref`, it works.

#### Creation of the fake

```csharp
A.Fake<IMyInterface<TestMessageType>>();
```

#### Interface declaration
```csharp
public interface IMyInterface<TMyType> where TMyType : Enum
{
    void Publish(in byte[] data);
}
```

#### Error Message
```
Failed to create fake of type IMyInterface`1[TestMessageType]:
        No usable default constructor was found on the type IMyInterface`1[TestMessageType].
        An exception of type Castle.DynamicProxy.ProxyGenerationException was caught during this call. Its message was:
        There was an error in static constructor on type Castle.Proxies.ObjectProxy. This is likely a bug in DynamicProxy. Please report it.
           at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value)
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
           at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
           at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
           at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.GenerateInterfaceProxy(Type typeOfProxy, ReadOnlyCollection`1 additionalInterfacesToImplement, IEnumerable`1 attributes, IFakeCallProcessorProvider fakeCallProcessorProvider) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 41
    
```

**Comment by blairconrad** [comment]
Hi, @eluchsinger. I'm sorry you're having a bad time.
This sounds very much like #1382, if I'm not mistaken. Sadly, due to a bug in dotnet core, there is no fix for this yet.
Unless you think there's a difference between this issue and #1382, I'm inclined to close this one.

**Comment by eluchsinger** [comment]
Looks like it might be the same one.

**Comment by thomaslevesque** [comment]
Hi @eluchsinger,

Not strictly related to the problem, but why do you declare the parameter as `in`? There's no benefit in this case, since `byte[]` is a reference type, so it will be passed by reference anyway.

**Comment by eluchsinger** [comment]
@thomaslevesque I only wrote this code to reproduce the error :)
