### ISSUE TITLE
Fake creation exception when creating a fake of a function that returns a class that is private

### ISSUE THREAD

**Issue by guerital** [FakeItEasy/FakeItEasy#1604]
We are updating to FakeItEasy 5.1.1 and the following test is now falling. I have created a sample to show the problem:

```
using System;
using FakeItEasy;
using NUnit.Framework;

namespace ConsoleApp1
{
    [TestFixture]
    public class NewClassTest
    {
        private class InnerClass
        {
        }

        [SetUp]
        public void SetUp()
        {
            var fake = A.Fake<Func<InnerClass>>();
        }

        [Test]
        public void Test1()
        {
        }
    }
}
```

When running the test we get the following error:

```
FakeItEasy.Core.FakeCreationException : 
  Failed to create fake of type System.Func`1[ConsoleApp1.NewClassTest+InnerClass]:
    Can not create proxy for type System.Func`1[[ConsoleApp1.NewClassTest+InnerClass, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] because type ConsoleApp1.NewClassTest+InnerClass is not accessible. Make it public, or internal and mark your assembly with [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")] attribute, because assembly mscorlib is strong-named.

   at FakeItEasy.Creation.CreationResult.get_Result() in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CreationResult.cs:line 43
   at FakeItEasy.Creation.DefaultFakeAndDummyManager.CreateFake(Type typeOfFake, Action`1 optionsBuilder) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\DefaultFakeAndDummyManager.cs:line 34
   at FakeItEasy.A.Fake[T]() in C:\projects\fakeiteasy\src\FakeItEasy\A.cs:line 32
   at ConsoleApp1.NewClassTest.SetUp() in C:\Users\italo.guerrieri\source\repos\ConsoleApp1\ConsoleApp1\NewClassTest.cs:line 18
```

The workaround is to make public the class "InnerClass"

**Comment by thomaslevesque** [comment]
Hi @guerital,

It's a change we made in [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.0.0): non-public delegates can no longer be faked (`Func<InnerClass>` is considered non-public because `InnerClass` is not public)
It used to work, but by accident rather than by design, because we use a different approach for faking delegates (Linq Expressions) than for classes or interfaces (Castle DynamicProxy). We intend to use DynamicProxy for faking delegates in the future, because it's much faster, but it doesn't support non-public types, so we anticipated the change and started rejecting non-public delegates.

**Comment by guerital** [comment]
Hi @thomaslevesque,

thanks for the answer

**Comment by gethari** [comment]
@guerital How did you fix this ?

**Comment by thomaslevesque** [comment]
@gethari Make sure any class you fake is public (or internal, using `InternalsVisibleTo` to make it visible to DynamicProxyGenAssembly2, as specified in the error message)
