### ISSUE TITLE
Is there a way to work with ReadOnlySpan

### ISSUE THREAD

**Issue by pingvinen** [FakeItEasy/FakeItEasy#1853]
Hi

I have tried searching the documentation and the issues, but I did not find anything other than what seems to be "internal" implementation discussions.

I have an interface that defines a method with a `ReadOnlySpan<char>` argument. My current predicament is that I need to define a return value from that method for my test.

Using `A.CallTo(() => thing.Method(A<ReadOnlySpan<char>>._)).Returns("something")` just states that a ReadOnlySpan cannot be used as an argument and if I run the test anyway, I get a `NotSupportedException`.

```
System.NotSupportedException
Specified method is not supported.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at FakeItEasy.ExpressionExtensions.Evaluate(Expression expression) in C:\projects\fakeiteasy\src\FakeItEasy\ExpressionExtensions.cs:line 28
   at FakeItEasy.Expressions.ExpressionArgumentConstraintFactory.<>c__DisplayClass13_0.<GetArgumentConstraintFromExpression>b__0() in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\ExpressionArgumentConstraintFactory.cs:line 167
   at FakeItEasy.Core.ArgumentConstraintTrap.TrapConstraintOrCreate(Action actionThatProducesConstraint, Func`1 defaultConstraintFactory) in C:\projects\fakeiteasy\src\FakeItEasy\Core\ArgumentConstraintTrap.cs:line 32
   at FakeItEasy.Expressions.ExpressionArgumentConstraintFactory.GetArgumentConstraintFromExpression(Expression expression, Type parameterType, Object& value) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\ExpressionArgumentConstraintFactory.cs:line 166
   at FakeItEasy.Expressions.ExpressionArgumentConstraintFactory.GetArgumentConstraint(ParsedArgumentExpression argument) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\ExpressionArgumentConstraintFactory.cs:line 30
   at FakeItEasy.Expressions.ExpressionCallMatcher..ctor(ParsedCallExpression parsedExpression, ExpressionArgumentConstraintFactory constraintFactory, MethodInfoManager methodInfoManager) in C:\projects\fakeiteasy\src\FakeItEasy\Expressions\ExpressionCallMatcher.cs:line 34
   at FakeItEasy.RootModule.<>c__DisplayClass1_0.<RegisterDependencies>g__ExpressionCallRuleFactory|3(ParsedCallExpression callSpecification) in C:\projects\fakeiteasy\src\FakeItEasy\RootModule.cs:line 112
   at FakeItEasy.Configuration.FakeConfigurationManager.CallTo[T](Expression`1 callSpecification) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\FakeConfigurationManager.cs:line 48
   at FakeItEasy.A.CallTo[T](Expression`1 callSpecification) in C:\projects\fakeiteasy\src\FakeItEasy\A.cs:line 161
   at test_unit.MyThing.SomethingTests..ctor()
```

I have tried matching with `A<string>._` and `A<char[]>._` as well, but either I get other warnings or I am back to the `NotSupportedException`

In my case I am dealing with large strings, so I would very much like to use `ReadOnlySpan`, but it is also critical code that I definitely want to verify does what it is supposed to do.

Any ideas?

If it is not possible to do at all, then I would like to suggest adding something to the documentation about it.

**Comment by thomaslevesque** [comment]
Hi @pingvinen, this is a limitation imposed by the compiler. [`ReadOnlySpan<T>` is a ref struct and can never live on the heap](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1?view=net-5.0#remarks); if it were allowed as a generic type argument, the compiler couldn't guarantee that it wouldn't end up being stored in an object's field and end up on the heap.

In this case, I don't see an easy workaround... You also can't use a placeholder value such as `default` (_CS8640 Expression tree cannot contain value of ref struct or restricted type 'ReadOnlySpan'._). Unless I'm missing something, the only option here is to test the name and parameters in a weakly typed fashion:

```csharp
A.CallTo(thing).Where(call => call.Method.Name == "Method" && maybeSomeOtherCondition).WithReturnType<string>().Returns("something");
```

**Comment by thomaslevesque** [comment]
Oops... that doesn't work either:

```csharp
    A.CallTo(thing).Where(call => call.Method.Name == "Method").WithReturnType<string>().Returns("something");
    ReadOnlySpan<char> x = "hello";
    var result = thing.Method(x);
```
throws InvalidProgramException: "Cannot create boxed ByRef-like values"

This might be an issue in Castle.Core...

**Comment by thomaslevesque** [comment]
BTW:

> if I run the test anyway

How? The code doesn't compile, how can you run the test anyway?

**Comment by pingvinen** [comment]
> > if I run the test anyway
> 
> How? The code doesn't compile, how can you run the test anyway?

It compiles with `A<char[]>._`. I have target=netcoreapp3.1 and sdk=5.x.

> this is a limitation imposed by the compiler.

I was starting to fear that based on similar discussions going on in all the other mocking frameworks out there. If you ever run into a pattern that works, which allows code to be tested and optimized using these new-ish types, please put it in the documentation :)

Btw... in my specific case I ended up implementing my interface in the test like so...


```csharp
public class MockableThing : IThing
{
	public string Method(ReadOnlySpan<char> data)
	{
		return MockableMethod(data.ToString());
	}

	public virtual string MockableMethod(string data)
	{
		throw new NotImplementedException();
	}
}

```

With a setup like..

```csharp
var thing = A.Fake<MockableThing>();

A.CallTo(() => thing.MockableMethod(A<string>._)).Returns("something");
```

This is not pretty and might not be feasible in all cases.

Thank you @thomaslevesque, for taking the time to work on `FakeItEasy` :)

**Comment by thomaslevesque** [comment]
That seems like a good solution in your case! Glad you were able to resolve the issue
