### ISSUE TITLE
FakeItEasy fails fake creation when called from a different `AppDomain` the the test runner's

### ISSUE THREAD

**Issue by ChristoWolf** [FakeItEasy/FakeItEasy#2040]
Hi, it's me again!

Let me preface this by saying that I love FakeItEasy, but I have no idea how to work around this issue on my side, as it is quite ingrained into FakeItEasy.

Whenever I try to execute an automated UI test (using [WinAppDriver](https://github.com/microsoft/WinAppDriver) + [the Appium .NET client](https://github.com/appium/dotnet-client)) for my WPF application, the application experiences an exception when **it** (i.e. not the test) calls FakeItEasy.

Unfortunately, due to company restrictions, I cannot share any code, but I think identifying the issue should be pretty straight forward.

Here is the exception (happens already when creating a `Fake`:
```
"Type": "System.TypeInitializationException",
"Message": "The type initializer for 'FakeItEasy.ServiceLocator' threw an exception.",
"StackTrace": "   at FakeItEasy.ServiceLocator.Resolve[T]() in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\ServiceLocator.cs:line 21
at FakeItEasy.A.get_FakeAndDummyManager() in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\A.cs:line 18
at FakeItEasy.A.Fake[T]() in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\A.cs:line 31
at <redacted>,
"InnerException": {
"Type": "System.UnauthorizedAccessException",
"Message": "Access to the path is denied.",
"StackTrace": "   at System.ConsolePal.WindowsConsoleStream.Write(ReadOnlySpan`1 buffer)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.TextWriter.SyncTextWriter.Write(Char value)
at System.Console.Write(Char value)
at FakeItEasy.DefaultOutputWriter.DefaultWriterState.Write(Char c) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\DefaultOutputWriter.cs:line 104
at FakeItEasy.DefaultOutputWriter.Write(String value) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\DefaultOutputWriter.cs:line 30
at FakeItEasy.Core.TypeCatalogue.Write(DefaultOutputWriter writer, Exception ex, String message) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\Core\\TypeCatalogue.cs:line 209
at FakeItEasy.Core.TypeCatalogue.Write(Exception ex, String message) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\Core\\TypeCatalogue.cs:line 203
at FakeItEasy.Core.TypeCatalogue.WarnFailedToLoadAssembly(String pathOrName, Exception ex) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\Core\\TypeCatalogue.cs:line 165
at FakeItEasy.Core.TypeCatalogue.TryLoadAssemblyIfItReferencesFakeItEasy(AssemblyName assemblyName, Assembly& assembly) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\Core\\TypeCatalogue.cs:line 156
at FakeItEasy.Core.TypeCatalogue.GetAllAssemblies(IEnumerable`1 extraAssemblyFiles) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\Core\\TypeCatalogue.cs:line 89
at FakeItEasy.Core.TypeCatalogue.Load(IEnumerable`1 extraAssemblyFiles) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\Core\\TypeCatalogue.cs:line 35
at FakeItEasy.RootModule.RegisterDependencies(IServiceRegistrar registrar) in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\RootModule.cs:line 33
at FakeItEasy.ServiceLocator..cctor() in D:\\a\\FakeItEasy\\FakeItEasy\\src\\FakeItEasy\\ServiceLocator.cs:line 10"
```

Used versions:
- FakeItEasy: 8.3.0
- .NET 8 (8.0.303 SDK)
- Windows 10, various

Hope you guys can help me with this, thanks!

**Comment by thomaslevesque** [comment]
Hi @ChristoWolf,

Sorry you're having trouble. To be honest I don't really understand how your setup works. Could you try to elaborate? I'm not familiar with Appium or WinAppDriver. How does it all work? Do the tests and the app run in the same process or in separate processes? How do AppDomains come into play here?

**Comment by thomaslevesque** [comment]
It's annoying that it fails to write to the console, because that means we don't know anything about the original exception is... Are you able to reproduce this in a debugger so that we can see the original exception details?

The fact that it fails to write to the console suggest something weird is going on. Maybe the AppDomain needs some specific permissions? (I haven't had to think about AppDomains in a very long time, I don't really remember how it works)

**Comment by blairconrad** [comment]
> Unfortunately, due to company restrictions, I cannot share any code, but I think identifying the issue should be pretty straight forward.

Can you write a small repro that does not include any of your company's code? Then we could witness the behaviour.

> Maybe I could [overwrite my application under test's FakeItEasy BootStrapper](https://fakeiteasy.github.io/docs/7.4.0/bootstrapper/#how-does-fakeiteasy-find-alternative-bootstrappers)

Sadly, I don't think the bootstrapper currently has an entry point that will fix/avoid your problem, as the exception is not coming out of the "extra filenames to scan" portion of the type catalogue initialization.

**Comment by ChristoWolf** [comment]
Hi!

I started a solution for reproducing the issue [here](https://github.com/ChristoWolf/fakeiteasy-appdomain-repro), but it does not happen there yet.
This requires WinAppDriver to be installed in its default installation path.

> Do the tests and the app run in the same process or in separate processes?

They run in separate processes.

> How do AppDomains come into play here?

Thus they have different app domains.

Unfortunately, I cannot give you more details right now because this repro MVP fails to reproduce it currently, but I'll keep trying.

This completely blocks my professional work :/

**Comment by ChristoWolf** [comment]
I managed to break on the original exception:
![image](https://github.com/user-attachments/assets/31545569-b9c2-46f3-ad62-9b12aed71565)

```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll: 'Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'
```

No idea why it would be looking for `Microsoft.Build`.

**Comment by ChristoWolf** [comment]
Found the cause:
In one of my project files I had `<PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />`.
Removing the `ExcludeAssets` and adding the
```
<PropertyGroup>
  <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
</PropertyGroup>
```
there did the trick, as the `Microsoft.Build` build artifacts are now copied to the build output directory, where FakeItEasy is then able to resolve them.

On the FakeItEasy side, this could be easily fixed by excluding any third-party packages from descovery.

**Comment by blairconrad** [comment]
Hi, ChristoWolf. Glad you found a solution.

> this could be easily fixed by excluding any third-party packages from discovery

the point is to discover third-party packages that have implemented extension points

> or even simply not throwing

Interesting idea, but if someone does implement an extension point and an error is encountered when scanning for it, they'll lose the notification from the throw.

I'm not sure there's a clear win, and am leaning against changing existing behaviour.

**Comment by thomaslevesque** [comment]
That doesn't explain why the code didn't have permission to write to the console though... there's something weird going on 🤔 

> On the FakeItEasy side, this could be easily fixed by excluding any third-party packages from discovery or even simply not throwing.

To be honest, I don't think this is a FakeItEasy problem at all. The assembly failed to load because it wasn't there, end of story...

The one thing we could consider changing is ignoring the error when writing to the console fails, but before we do that, I'd rather have a better understanding of why it fails.

**Comment by ChristoWolf** [comment]
> I'm not sure there's a clear win, and am leaning against changing existing behaviour.

I understand that, it's just weird to me that FakeItEasy tries to harvests such assemblies.

> That doesn't explain why the code didn't have permission to write to the console though...

There I'm still pretty sure that it's related to `AppDomain`s.
I'll try to reproduce the issue, now that I know how to provoke the exception.

**Comment by blairconrad** [comment]
> it's just weird to me that FakeItEasy tries to harvests such assemblies.

In case it helps you understand why this happens, here's [the documentation on the extension points](https://fakeiteasy.github.io/docs/8.3.0/scanning-for-extension-points/), which are kinds of [plugins](https://en.wikipedia.org/wiki/Plug-in_(computing)). FakeItEasy looks for user-supplied code to enhance the user's test-writing (and output-reading) experience.

**Comment by thomaslevesque** [comment]
> I understand that, it's just weird to me that FakeItEasy tries to harvests such assemblies.

I think it tries to load one of your assemblies. That assembly references Microsoft.Build, but since Microsoft.Build can't be found, your assembly fails to load.

**Comment by ChristoWolf** [comment]
Hey everyone!

Thanks for all the replies!

I am of course aware of everything that you guys brought up, let me clarify what I am proposing:

The issue for me is not the loading failure itself, that's perfectly fine, it would just be better to have more reliable dev feedback (e.g. no error writing failure).
My main point is that things like Microsoft.Build should not contribute to extension point discovery, because there is no sense to it.

> The assembly failed to load because it wasn't there, end of story...

Clearly, but why would this one in particular be considered at all?

**Comment by blairconrad** [comment]
Hey, @ChristoWolf.

> My main point is that things like Microsoft.Build should not contribute to extension point discovery, because there is no sense to it.

You say there's no sense to it. I assume you say this because there are no FakeItEasy extension points defined in Microsoft.Build. This is true, but for any given assembly, we can't know there's nothing in it that contributes until we load it and look for the extension points.

> Clearly, but why would \[Microsoft.Build\] in particular be considered at all?

You mentioned 

> In one of my project files I had <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />.

Which sounds like it set up the dependency between the project and Microsoft.Build. Microsoft.Build wasn't a loaded assembly, but was referenced from the initial project, so [TypeCatalogue.GetAllAssemblies](https://github.com/FakeItEasy/FakeItEasy/blob/fba7c6b3ecb84693fa4c8bb020ff65268144db37/src/FakeItEasy/Core/TypeCatalogue.cs#L71-L100) decided to peek at Microsoft.Build to see if it happened to be something that contained extension points.

> Are assemblies which are not physically present at all lead to failures?

If I understand correctly, I would expect so. One could test it by building a project, removing an assembly and running a test.

> What about statically linked stuff?

Sorry, I don't understand the question as is. Can you expand?

> Could it be useful to support general assembly discovery configuration?

Potentially yes. The existing bootstrapper was a first step down this road, I suppose. It was mostly added to improve startup performance when there were a lot of external assemblies that were known not to contribute extension points. Although until now there's been no demand, I think further customizing the assembly discovery process is in line with this approach.

> Why would the failure get written to the console?

Same reason most software does what it does. It's a thing we did when implementing a feature and it worked well enough until it didn't.
I was thinking about this on the weekend and wondered why we didn't throw an exception instead.

**Comment by ChristoWolf** [comment]
> You say there's no sense to it. I assume you say this because there are no FakeItEasy extension points defined in Microsoft.Build. This is true, but for any given assembly, we can't know there's nothing in it that contributes until we load it and look for the extension points.

Exactly, and, as you said, that's why I think it would be best to exclude this library.

> Which sounds like it set up the dependency between the project and Microsoft.Build. Microsoft.Build wasn't a loaded assembly, but was referenced from the initial project, so TypeCatalogue.GetAllAssemblies decided to peek at Microsoft.Build to see if it happened to be something that contained extension points.

Exactly, that's also my understanding.

> Sorry, I don't understand the question as is. Can you expand?

To some degree, static libraries (e.g. .lib or IL stuff) can be linked/embedded into assemblies in C#.
I would guess that this breaks the assembly discovery.
Also, what about AOT or obfuscated stuff which breaks reflection?

> Same reason most software does what it does.

Again, none of this is supposed to be critique of any design choices, I absolutely love the library!
I just think that there are some edge case quirks which could be improved upon.

**Comment by blairconrad** [comment]
> Exactly, and, as you said, that's why I think it would be best to exclude \[Microsoft.Build\].

I hear you, but have essentially no interest in maintaining an "exclude list" of libraries. I think "don't reference the library if you're not including/providing it" is a not-unreasonable restriction to put on a client.

> To some degree, static libraries (e.g. .lib or IL stuff) can be linked/embedded into assemblies in C#.
> I would guess that this breaks the assembly discovery.
> Also, what about AOT or obfuscated stuff which breaks reflection?

I've no idea. All of these things may in fact be terrible (but we used to embed Castle.Core and that didn't cause problems; maybe the mechanism is different). But I haven't time or interest in chasing down hypothetical problems that may never affect anyone. If someone showed up with a legitimate use case that surfaced a lack in FakeItEasy, I'd be inclined to investigate.

> I just think that there are some edge case quirks which could be improved upon.

No doubt. So far the one that I'm seeing is that a failure to load assemblies is, in some cases, not well-reported. Speaking for myself, I'd be disposed to consider a fix to the problem, if we had a concrete reproduction. (And even more disposed to accept a pull request that reproduced the problem and fixed it.)

**Comment by ChristoWolf** [comment]
> I think "don't reference the library if you're not including/providing it" is a not-unreasonable restriction to put on a client.

I agree, it's just a restriction that comes from my team, but we are looking into clean work-arounds.

> Speaking for myself, I'd be disposed to consider a fix to the problem, if we had a concrete reproduction.

I'll try to do so next week, will keep you updated!
