### ISSUE TITLE
Initialize exception 'FakeItEasy.Core.FakeScope' --> 'System.Core, Version=5.0.5.0 not found (Windows 10 Unit Test Project)

### ISSUE THREAD

**Issue by jlouros** [FakeItEasy/FakeItEasy#491]
HI there,

I am just playing around with a new Windows 10 application. For Win10 UnitTest project I was trying to use FakeItEasy to mock a particular object, when I get this exception every time I try to use it. (using version 2.0.0 Beta009)

	Test Name:	Initializer
	Test FullName:	MyWin10App.Tests.Workers.MyWin10AppWorkerTests.Initializer
	Test Source:	C:\Code\MyWin10App\MyWin10App.Tests\Workers\MyWin10AppWorkerTests.cs : line 21
	Test Outcome:	Failed
	Test Duration:	0:00:00.0305306

	Result StackTrace:	
	at FakeItEasy.ImportsModule.<RegisterDependencies>b__1(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.UnresolvedState.Resolve(DictionaryContainer container)
	   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.Resolve(DictionaryContainer container)
	   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass1`1.<Register>b__0(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
	   at FakeItEasy.ServiceLocator.Resolve[T]()
	   at FakeItEasy.Core.FakeScope.RootScope..ctor()
	   at FakeItEasy.Core.FakeScope..cctor()
	 --- End of inner exception stack trace ---
		at FakeItEasy.RootModule.<RegisterDependencies>b__2(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass1`1.<Register>b__0(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
	   at FakeItEasy.ServiceLocator.Resolve[T]()
	   at FakeItEasy.RootModule.<RegisterDependencies>b__3(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass1`1.<Register>b__0(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
	   at FakeItEasy.ServiceLocator.Resolve[T]()
	   at FakeItEasy.RootModule.<RegisterDependencies>b__1a(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass1`1.<Register>b__0(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
	   at FakeItEasy.ServiceLocator.Resolve[T]()
	   at FakeItEasy.RootModule.<RegisterDependencies>b__19(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass1`1.<Register>b__0(DictionaryContainer c)
	   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
	   at FakeItEasy.ServiceLocator.Resolve[T]()
	   at FakeItEasy.A.Fake[T]()
	   at MyWin10App.Tests.Workers.MyWin10AppWorkerTests.Initializer() in C:\Code\MyWin10App\MyWin10App.Tests\Workers\MyWin10AppWorkerTests.cs:line 23
	Result Message:	Test method MyWin10App.Tests.Workers.MyWin10AppWorkerTests.Initializer threw exception: 
	System.TypeInitializationException: The type initializer for 'FakeItEasy.Core.FakeScope' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=5.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.

**Comment by blairconrad** [comment]
Hi, @jlouros. Thanks for raising this.

> I was trying to use FakeItEasy to mock a particular object,

Does this mean you're able to fake other objects, or does this error occur any time FakeItEasy is used?

Unfortunately, I don't keep up with the bleeding edge technologies, so I may not be of much use. Your problem reminds me of the StackOverlow question [Winrt Testproject using FakeItEasy](http://stackoverflow.com/questions/25260457/winrt-testproject-using-fakeiteasy), but I fear that still won't help…

In the interest of aiding anyone who may have some insight, do you have a sample solution you can share?

**Comment by jlouros** [comment]
Hey @blairconrad. Thank you for the quick response.

I have seen this error every time I use FakeItEasy.

The StackOverflow question you mentioned, totally correlates with the problem I have seen. Currently, Windows 10 projects compilation generates a Portable Class Library targeting Windows 8.1, so if we can fix one, we can fix the other.

Meanwhile I will work on a project that replicates the issue. I will post a link as soon as possible.

**Comment by blairconrad** [comment]
Hm. Now I wonder if you need to go the effort of posting a project.
Given that Win10 is emitting PCL targeting Windows 8.1, I think https://github.com/FakeItEasy/FakeItEasy/issues/214#issuecomment-59406766 applies:

> Unfortunately FakeItEasy won't support PCL, win81 or wpa81 until Castle.Core does, or if we switch
> to another dynamic proxy provider which does. Realistically I don't see either of these things
> happening soon :wink:. See castleproject/Core#41

**Comment by ardonjr** [comment]
It is now January 2016.. and I'm still running into this issue. Does that mean that FakeItEasy is never going to be usable on a Universal W10 project? Because that would be a sad thing.

**Comment by adamralph** [comment]
@ardonjr FakeItEasy is completely dependent on Castle.Core. I raised [an issue](https://github.com/castleproject/Core/issues/41) to get PCL support into Castle.Core but as you can see, the owners stated that it's not possible and closed the issue.

There is an [open issue](https://github.com/castleproject/Core/issues/90) for .NET core support in Castle.Core. If that is done, depending on the method chosen (e.g. it may target one of the cross platform [netstandard](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md) platforms), universal win10 support may come with that.

If you are interested in pushing for this, the place to do so is over at Castle.Core. We cannot support a given platform until Castle.Core supports it.

**Comment by ardonjr** [comment]
@adamralph That explains a lot.. but is still a sad thing though. I used FakeItEasy with much joy.. until now I suppose. 
I did a quick checked around the internet but there is no mocking framework available for UWP 10 due to this same issue. So I guess we'll have to find a way to mock things our self now.. thanks Microsoft! 

Anyhow.. thanks for the fast reply.

**Comment by adamralph** [comment]
We're glad you've enjoyed FIE so much :smile: 

Yes, I guess this is a general problem in .NET with many of the new platforms. My main hope in this area is that the new netstandards initiative unifies everything and hopefully Castle.Core will come to support that, so that FIE and the rest of the Castle.Core based framworks can also support it. That way, you'll be able to write the bulk of your app in portable code (at least the part that warrants unit testing and mocking) and only the UI layer in a device specific platform.
