### ISSUE TITLE
Proxy generator gets confused by extension method overloads with same name 

### ISSUE THREAD

**Issue by TimLovellSmith** [FakeItEasy/FakeItEasy#681]
Code:

```c#
public interface IProvisionServiceConnection
{
    Task EnqueueAsync(string functionName, object msg, string scope);
}

public static class IProvisionServiceConnectionExtensions
{
    public static Task EnqueueAsync(
        this IProvisionServiceConnection conn,
        ProvisioningOperation operation,
        object msg,
        string scope)
    {
        return conn.EnqueueAsync(operation.ToString(), msg, scope);
    }
}

A.CallTo(() => enqueuer.EnqueueAsync("Create", A<object>._, dep.Id.ToString()))
    .MustHaveHappened();
```

Problem - assert fails, because it assumes the extension method will be called, even though C# compiler could tell by parameter types that the interface method will be called.

Result StackTrace:	
```
at FakeItEasy.Configuration.DefaultInterceptionAsserter.AssertThatMethodCanBeInterceptedOnInstance(MethodInfo method, Object callTarget)
   at FakeItEasy.Configuration.FakeConfigurationManager.CallTo[T](Expression`1 callSpecification)
   at CreatePendingOpTests.<CreatePendingOp_Delivery>d__1.MoveNext() in CreatePendingOpTests.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
FakeItEasy.Configuration.FakeConfigurationException : 

  The current proxy generator can not intercept the specified method for the following reason:
    - Sealed methods can not be intercepted.
```

**Comment by blairconrad** [comment]
@TimLovellSmith, I tried to reproduce, but failed to do so. What am I doing wrong?

```c#
public interface IProvisionServiceConnection
{
    Task EnqueueAsync(string functionName, object msg, string scope);
}

public enum ProvisioningOperation
{
    Create
}

public static class IProvisionServiceConnectionExtensions
{
    public static Task EnqueueAsync(this IProvisionServiceConnection conn, ProvisioningOperation operation,
        object msg, string scope)
    {
        return conn.EnqueueAsync(operation.ToString(), msg, scope);
    }
}

public class ConfusingExtensionMethod
{
    [Fact]
    public void Should_not_be_confused()
    {
        var enqueuer = A.Fake<IProvisionServiceConnection>();

        enqueuer.EnqueueAsync(ProvisioningOperation.Create, new object(), "giraffe");

        A.CallTo(() => enqueuer.EnqueueAsync("Create", A<object>._, "hippo"))
            .MustHaveHappened();
    }
}
```

produces 

```
FakeItEasy.ExpectationException

  Assertion failed for the following call:
    FakeItEasyQuestionsVS2015.IProvisionServiceConnection.EnqueueAsync("Create", <Ignored>, "hippo")
  Expected to find it at least once but found it #0 times among the calls:
    1: FakeItEasyQuestionsVS2015.IProvisionServiceConnection.EnqueueAsync(
          functionName: "Create",
          msg: System.Object,
          scope: "giraffe")
```

**Comment by TimLovellSmith** [comment]
Ah... I think I found the problem is that I wasn't actually passing a Fake. :p
So it's more of a confusing error message.

Modified repro code

```
    public interface IProvisionServiceConnection
    {
        Task EnqueueAsync(string functionName, object msg, string scope);
    }

    class ProvisionServiceConnection : IProvisionServiceConnection
    {
        public Task EnqueueAsync(string functionName, object msg, string scope)
        {
            return Task.Delay(0);
        }
    }

    public enum ProvisioningOperation
    {
        Create
    }

    public static class IProvisionServiceConnectionExtensions
    {
        public static Task EnqueueAsync(this IProvisionServiceConnection conn, ProvisioningOperation operation,
            object msg, string scope)
        {
            return conn.EnqueueAsync(operation.ToString(), msg, scope);
        }
    }

    class Program
    {
        public static void Main()
        {
            var enqueuer = new ProvisionServiceConnection();

            enqueuer.EnqueueAsync(ProvisioningOperation.Create, new object(), "giraffe");

            A.CallTo(() => enqueuer.EnqueueAsync("Create", A<object>._, "hippo"))
                .MustHaveHappened();
        }
    }
```

**Comment by TimLovellSmith** [comment]
No, that's not it, that was a different error after all, just same exception type.

**Comment by TimLovellSmith** [comment]
No that *was it*. I was just confused about what the error message actually was. 😄

**Comment by blairconrad** [comment]
I think I have whiplash.
Sounds like we can close?

**Comment by TimLovellSmith** [comment]
Deleted those whiplash causing comments it an attempt to fix the information imparted by the thread... yes I don't particularly care if this issue gets fixed.

**Comment by adamralph** [comment]
The exception message makes sense, although perhaps it isn't as clear as it could be. Perhaps better would be

> Non-virtual methods can not be intercepted.

or even better

> The object is not a fake.

**Comment by blairconrad** [comment]
The wording you suggest may be better, @adamralph, but will everyone understand that an interface method is virtual? An abstract one? I'm not sure.

I do like the idea of `FakeConfigurationManager.AssertThatMemberCanBeIntercepted` or some nearby code indicating when the target of `A.CallTo[Set]` is not a fake. I think that's a big win.

**Comment by adamralph** [comment]
I've raised #682.

Thanks @TimLovellSmith for bringing this to our attention.

**Comment by TimLovellSmith** [comment]
>The object is not a fake.

+1

**Comment by blairconrad** [comment]
@TimLovellSmith, @adamralph created #682 to update the exception message. Is there more work to be done on this issue? (You reopened it.)

**Comment by TimLovellSmith** [comment]
Oh I didn't notice 682, sorry.
